In [2]:
! pip install mlxtend


In [3]:
import numpy as np
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

In [5]:
data = pd.read_excel('archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx')

FileNotFoundError: ignored

In [6]:
data = pd.read_excel('/content/drive/MyDrive/Online Retail.xlsx')

In [7]:
data.head()

InvoiceNo StockCode  ... CustomerID         Country
0    536365    85123A  ...    17850.0  United Kingdom
1    536365     71053  ...    17850.0  United Kingdom
2    536365    84406B  ...    17850.0  United Kingdom
3    536365    84029G  ...    17850.0  United Kingdom
4    536365    84029E  ...    17850.0  United Kingdom

[5 rows x 8 columns]

In [8]:
data.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [9]:
data.shape

(541909, 8)

In [11]:
data.isnull().values.any()

True

In [12]:
data.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

## Preprocessing

In [13]:
data['Description'] = data['Description'].str.strip()

In [14]:
data['InvoiceNo'].value_counts()

573585    1114
581219     749
581492     731
580729     721
558475     705
          ... 
548216       1
570822       1
558261       1
558268       1
551538       1
Name: InvoiceNo, Length: 25900, dtype: int64

In [15]:
# Dropping the rows without any invoice number
data.dropna(axis = 0, subset =['InvoiceNo'], inplace = True)
data['InvoiceNo'] = data['InvoiceNo'].astype('str')

In [16]:
data.shape

(541909, 8)

In [17]:
data = data[~data['InvoiceNo'].str.contains('C')]

In [18]:
data.shape

(532621, 8)

In [20]:
data[data['InvoiceNo'].str.contains('C')]

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [21]:
data.Country.unique()

array(['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Finland',
       'Austria', 'Bahrain', 'Israel', 'Greece', 'Hong Kong', 'Singapore',
       'Lebanon', 'United Arab Emirates', 'Saudi Arabia',
       'Czech Republic', 'Canada', 'Unspecified', 'Brazil', 'USA',
       'European Community', 'Malta', 'RSA'], dtype=object)

In [22]:
basket_France = (data[data['Country'] =="France"]
.groupby(['InvoiceNo', 'Description'])['Quantity']
.sum().unstack().reset_index().fillna(0)
.set_index('InvoiceNo'))

In [37]:
data.groupby(['InvoiceNo', 'Description'])['Quantity'].sum()


InvoiceNo  Description                        
536365     CREAM CUPID HEARTS COAT HANGER          8
           GLASS STAR FROSTED T-LIGHT HOLDER       6
           KNITTED UNION FLAG HOT WATER BOTTLE     6
           RED WOOLLY HOTTIE WHITE HEART.          6
           SET 7 BABUSHKA NESTING BOXES            2
                                                  ..
581587     PLASTERS IN TIN STRONGMAN              12
           SPACEBOY LUNCH BOX                     12
A563185    Adjust bad debt                         1
A563186    Adjust bad debt                         1
A563187    Adjust bad debt                         1
Name: Quantity, Length: 520338, dtype: int64

In [34]:
data[data['Country'] =="France"].groupby(['InvoiceNo', 'Description'])['Quantity'].sum()

InvoiceNo  Description                    
536370     ALARM CLOCK BAKELIKE GREEN         12
           ALARM CLOCK BAKELIKE PINK          24
           ALARM CLOCK BAKELIKE RED           24
           CHARLOTTE BAG DOLLY GIRL DESIGN    20
           CIRCUS PARADE LUNCH BOX            24
                                              ..
581587     CIRCUS PARADE LUNCH BOX            12
           PACK OF 20 SPACEBOY NAPKINS        12
           PLASTERS IN TIN CIRCUS PARADE      12
           PLASTERS IN TIN STRONGMAN          12
           SPACEBOY LUNCH BOX                 12
Name: Quantity, Length: 8372, dtype: int64

In [24]:
def hot_encode(x):
  if(x<= 0):
    return 0
  if (x>=1):
    return 1

In [25]:
basket_encoded = basket_France.applymap(hot_encode)
basket_France = basket_encoded

In [26]:
basket_France.head()

Description  10 COLOUR SPACEBOY PEN  ...  ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo                            ...                                 
536370                            0  ...                                0
536852                            0  ...                                0
536974                            0  ...                                0
537065                            0  ...                                0
537463                            0  ...                                0

[5 rows x 1563 columns]

## Building Model

In [27]:
# Building the model
frq_items = apriori(basket_France, min_support = 0.1, use_colnames = True)
# Collecting the inferred rules in a dataframe
rules = association_rules(frq_items, metric ="lift", min_threshold = 1)
rules = rules.sort_values(['confidence', 'lift'], ascending =[False, False])

In [28]:
rules

antecedents  ... conviction
41                    (SET/6 RED SPOTTY PAPER PLATES)  ...  21.556122
43           (SET/6 RED SPOTTY PAPER PLATES, POSTAGE)  ...  18.107143
34                (STRAWBERRY LUNCH BOX WITH CUTLERY)  ...   3.755102
27               (ROUND SNACK BOXES SET OF4 WOODLAND)  ...   3.637755
40                      (SET/6 RED SPOTTY PAPER CUPS)  ...   7.852041
10                    (PLASTERS IN TIN CIRCUS PARADE)  ...   1.936224
18                               (RABBIT NIGHT LIGHT)  ...   1.929705
22                    (RED TOADSTOOL LED NIGHT LIGHT)  ...   1.851474
42             (SET/6 RED SPOTTY PAPER CUPS, POSTAGE)  ...   6.688776
4                                (LUNCH BAG WOODLAND)  ...   1.799320
30                      (SET/6 RED SPOTTY PAPER CUPS)  ...   1.584184
33                    (SET/6 RED SPOTTY PAPER PLATES)  ...   1.466837
0                            (LUNCH BAG APPLE DESIGN)  ...   1.437500
24                         (REGENCY CAKESTAND 3 TIER)  ...   1.437500
14                         (PLASTERS IN TIN SPACEBOY)  ...   1.408163
20                         (RED RETROSPOT MINI CASES)  ...   1.408163
44  (SET/6 RED SPOTTY PAPER CUPS, SET/6 RED SPOTTY...  ...   1.408163
28               (SET/20 RED RETROSPOT PAPER NAPKINS)  ...   1.356009
16                 (PLASTERS IN TIN WOODLAND ANIMALS)  ...   1.209576
6                  (LUNCH BOX WITH CUTLERY RETROSPOT)  ...   1.194805
47                    (SET/6 RED SPOTTY PAPER PLATES)  ...   4.413265
39                    (SET/6 RED SPOTTY PAPER PLATES)  ...   4.336735
2                           (LUNCH BAG RED RETROSPOT)  ...   1.173469
38               (SET/20 RED RETROSPOT PAPER NAPKINS)  ...   3.780612
36               (SET/20 RED RETROSPOT PAPER NAPKINS)  ...   3.736395
12                         (PLASTERS IN TIN SPACEBOY)  ...   3.443878
46                      (SET/6 RED SPOTTY PAPER CUPS)  ...   3.443878
37                      (SET/6 RED SPOTTY PAPER CUPS)  ...   3.345481
13                 (PLASTERS IN TIN WOODLAND ANIMALS)  ...   2.221939
9                     (PLASTERS IN TIN CIRCUS PARADE)  ...   2.104592
8                  (PLASTERS IN TIN WOODLAND ANIMALS)  ...   2.063681
19                                          (POSTAGE)  ...   1.035606
23                                          (POSTAGE)  ...   1.032199
26                                          (POSTAGE)  ...   1.043599
11                                          (POSTAGE)  ...   1.030950
17                                          (POSTAGE)  ...   1.011075
3                                           (POSTAGE)  ...   1.008260
31                                          (POSTAGE)  ...   1.018399
35                                          (POSTAGE)  ...   1.032413
15                                          (POSTAGE)  ...   1.014406
21                                          (POSTAGE)  ...   1.014406
7                                           (POSTAGE)  ...   1.008403
29                                          (POSTAGE)  ...   1.012467
32                                          (POSTAGE)  ...   1.014476
1                                           (POSTAGE)  ...   1.013514
25                                          (POSTAGE)  ...   1.013514
5                                           (POSTAGE)  ...   1.018446
45                                          (POSTAGE)  ...   1.012559

[48 rows x 9 columns]

#PCA


In [39]:
from sklearn.decomposition import PCA

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [40]:
k = 1
pca = PCA(k)

In [41]:
data = np.array([[2.5, 2.4], [0.5, 0.7],[2.2, 2.9],[1.9, 2.2],[3.1, 3.0], [2.3, 2.7],[2, 1.6],[1.0, 1.1],[1.5,1.6],
[1.1,0.9]])

In [45]:
np.matrix(data)

matrix([[2.5, 2.4],
        [0.5, 0.7],
        [2.2, 2.9],
        [1.9, 2.2],
        [3.1, 3. ],
        [2.3, 2.7],
        [2. , 1.6],
        [1. , 1.1],
        [1.5, 1.6],
        [1.1, 0.9]])

In [48]:
print(f"Reducted form: \n {pca.fit_transform(data)}")

Reducted form: 
 [[-0.82797019]
 [ 1.77758033]
 [-0.99219749]
 [-0.27421042]
 [-1.67580142]
 [-0.9129491 ]
 [ 0.09910944]
 [ 1.14457216]
 [ 0.43804614]
 [ 1.22382056]]


In [50]:
M = np.mean(data.T, axis=1)

In [51]:
M

array([1.81, 1.91])

In [52]:
covariance_matrix = data - M

In [53]:
print(covariance_matrix)

[[ 0.69  0.49]
 [-1.31 -1.21]
 [ 0.39  0.99]
 [ 0.09  0.29]
 [ 1.29  1.09]
 [ 0.49  0.79]
 [ 0.19 -0.31]
 [-0.81 -0.81]
 [-0.31 -0.31]
 [-0.71 -1.01]]


In [55]:
from numpy import cov
from numpy.linalg import eig

In [57]:
V = cov(covariance_matrix.T)
print(V)

[[0.61655556 0.61544444]
 [0.61544444 0.71655556]]


In [58]:
values, vectors = eig(V)
print(vectors)
print(values)

[[-0.73517866 -0.6778734 ]
 [ 0.6778734  -0.73517866]]
[0.0490834  1.28402771]


In [61]:
P = vectors.T.dot(covariance_matrix.T)
print(P.T)

[[-0.17511531 -0.82797019]
 [ 0.14285723  1.77758033]
 [ 0.38437499 -0.99219749]
 [ 0.13041721 -0.27421042]
 [-0.20949846 -1.67580142]
 [ 0.17528244 -0.9129491 ]
 [-0.3498247   0.09910944]
 [ 0.04641726  1.14457216]
 [ 0.01776463  0.43804614]
 [-0.16267529  1.22382056]]


In [62]:
print('\nLargest eigen value column index')
col = np.argmax(np.max(P, axis=1))
print(col)
print('\nfinal 1-D Space Data:')
print(P.T[:, col])


Largest eigen value column index
1

final 1-D Space Data:
[-0.82797019  1.77758033 -0.99219749 -0.27421042 -1.67580142 -0.9129491
  0.09910944  1.14457216  0.43804614  1.22382056]
